In [1]:
#1. Importing libraries
import numpy as np
import pandas as pd

In [2]:
#2.Importing datasets
df=pd.read_csv('Data.csv')
type(df)

pandas.core.frame.DataFrame

In [16]:
#3.fetching x,y
X=df.iloc[:,:-1].values  #by convention X ->caps y->small
y=df.iloc[:,-1].values #.values converts series to array
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [4]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [5]:
y=df.iloc[:,-1].values
y                       #metrics of dependent variable is y and independent x

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [6]:
#4.Handling missing data
from sklearn.preprocessing import Imputer  #sklearn=package, preprocessing=library, imputer=class
im=Imputer(missing_values='NaN',strategy='mean',axis=0) #invoking constructor of Imputer
X[:,1:3]=im.fit_transform(X[:,1:3]) #method invoking, fillna works on dataframe here we are working on aray
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [7]:
#5.Handling categorical data
# country and purchased are categorical data, we are going to replace it with numeric data becoz only numeic data is processed
from sklearn.preprocessing import LabelEncoder,OneHotEncoder  #explore why onehot.. is needed
le_X=LabelEncoder()  #no para needed,le_X =object of x
le_y=LabelEncoder()
ohe=OneHotEncoder(categorical_features=[0])#column on which (0) we are applying categorical features
X[:,0]=le_X.fit_transform(X[:,0])
X=ohe.fit_transform(X).toarray()
y=le_y.fit_transform(y)
X   #categorical data changed into numeric ones


array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.00000000e+01,
        5.40000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        5.80000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
        5.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
        8.30000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70000000e+01,
        6.70000000e+04]])

In [8]:
X

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.00000000e+01,
        5.40000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        5.80000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
        5.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
        8.30000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70000000e+01,
        6.70000000e+04]])

In [9]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1], dtype=int64)

In [11]:
#6.SPLITTING TEST TRAIN
from sklearn.cross_validation import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=39)
len(y_test)  #3 data to test
X_train  #7 data to train

array([[0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
        8.30000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        5.80000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
        5.20000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70000000e+01,
        6.70000000e+04]])

In [14]:
#7.Feature engineering
from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.fit_transform(X_test)
X_test

array([[-0.70710678,  1.41421356, -0.70710678, -0.53916387, -0.47176767],
       [-0.70710678, -0.70710678,  1.41421356, -0.86266219, -0.91870546],
       [ 1.41421356, -0.70710678, -0.70710678,  1.40182605,  1.39047313]])

In [17]:
X_train

array([[-0.8660254 ,  1.58113883, -0.63245553,  2.04480597,  1.89783978],
       [ 1.15470054, -0.63245553, -0.63245553, -1.14914715, -0.77577172],
       [-0.8660254 , -0.63245553,  1.58113883, -0.51035653, -0.45493834],
       [-0.8660254 , -0.63245553,  1.58113883, -0.34474415, -1.41743847],
       [-0.8660254 ,  1.58113883, -0.63245553, -0.08449611, -0.15787039],
       [ 1.15470054, -0.63245553, -0.63245553,  0.76722472,  0.72145072],
       [ 1.15470054, -0.63245553, -0.63245553, -0.72328674,  0.18672842]])